---
title: "Research"
---

## Job Market Paper

* [**"Infrastructure, Institutions, and the Conservation of Biodiversity in India"**](/pdf/rmadhok_jmp_2022.pdf) (*Job Market Paper*)  
(Previously titled "The Development-Biodiversity Tradeoff in India's Forests")

    + **Abstract**: Biodiversity in the tropics is severely threatened by land use change. This paper studies how infrastructure expansion degrades biodiversity in India and the role of local institutions in mitigating the tradeoff. Combining new data on infrastructure-driven deforestation with one million birdwatching diaries, and using within-observer variation for identification, I document a sizeable infrastructure-biodiversity tradeoff. Transport, irrigation, resettlement camps, and mining projects account for 20\% of total species loss.  Publicly owned projects are especially harmful, and species diversity does not recover in the medium run. Lastly, I find that species loss is more than halved when local institutions enable marginalized communities, who are excluded from project planning, to mobilize around their interests. Informed consent by indigenous tribes is a key mechanism, underscoring the importance of grassroots institutions for balancing development and conservation.

  + **Presented At**: NBER Summer Institute (Environment & Energy Economics), AERE Summer Conference, PacDev, Camp Resources, Columbia Sustainable Development Workshop, Canadian Resource and Environmental Economics Association
  
  + **Media**: [Ideas of India podcast](https://www.discoursemagazine.com/politics/2022/09/29/ideas-of-india-the-development-biodiversity-tradeoff-in-india/)

## Working Papers

* [**"Internal Migration and the Re-organization of Agriculture"**](/pdf/2022_rural_urban_agriculture.pdf) <-- **latest version!**   
(with [Frederik Noack](https://frederiknoack.landfood.ubc.ca/), [Mushfiq Mobarak](https://faculty.som.yale.edu/mushfiqmobarak/), and [Olivier Deschenes](https://www.olivierdeschenes.org/)) [[*Yale EGC WP #1095*]](/pdf/2022_rural_urban_agriculture_egc.pdf)

    + **Abstract**: This paper studies the response of agricultural production to rural labor loss during the process of urbanization. Using household microdata from India and exogenous variation in migration induced by urban income shocks interacted with distance to cities, we document sharp declines in crop production among migrant-sending households residing near cities. Households with migration opportunities do not substitute agricultural labour with capital, nor do they adopt new agricultural machinery. Instead, they divest from agriculture altogether and cultivate less land. We use a two-sector general equilibrium model with crop and land markets to trace the ensuing spatial reorganization of agriculture. Other non-migrant village residents expand farming (land market channel) and farmers in more remote villages with fewer migration opportunities adopt yield-enhancing technologies and produce more crops (crop market channel). Counterfactual simulations show that over half of the aggregate food production losses driven by urbanization is mitigated by these spillovers. This leads to a spatial reorganization in which food production moves away from urban areas and towards remote areas with low emigration.
    
     + **Presented At**: OSWEET, Western Economic Association

* [**"The Long-Run Health Consequences of Coal Power Plants"**](/pdf/power_plants_india.pdf)  
(with [Rohini Pande](https://campuspress.yale.edu/rpande/), [Anish Sugathan](https://www.iima.ac.in/web/faculty/faculty-profiles/anish-sugathan) and Kevin Rowe)

  + **Abstract**: This paper quantifies the long-run effects of India’s dramatic expansion of coal-fired electric
power plants from 1970 to 2017 on neonatal, infant, and child health. We use a particle trajectory model that draws wind-driven patterns of emissions dispersion from power plants to construct an exogenous measure of cumulative pollution exposure over three decades. Our measure of historic power plant exposure predicts present-day air quality three to six times better than conventional wind-direction instruments in the literature. A one standard deviation increase in long-run exposure to power plant emissions increases neonatal, infant, and child deaths by 0.6 (2 percent of the mean), 0.9 (1.9 percent), and 1.3 (2.2 percent) per 1000 live births, respectively. These effects are largely driven by exposure in-utero, as well as exposure to private power plant clusters forming between 1992-2005. We find no evidence of differential economic development between more- and less-exposed districts, ruling out adaptation, and underscoring pollution as the main mechanism.

## Publications

* [**Ruling The Roost: Avian Species Reclaim Urban Habitat During India's COVID-19 Lockdown**](https://www.sciencedirect.com/science/article/pii/S0006320722001501)   
(with [Sumeet Gulati](https://sumeetgulati.landfood.ubc.ca/)). *Biological Conservation, 2022*
<ul> <li style="list-style-type: none;"> 
<details> <summary>[Click for Abstract] [[PDF]](/pdf/2022_ruling_the_roost.pdf)</summary>
As we retreated to our dwellings in the “anthropause” of spring 2020, were the wildlife sightings in previously crowded spaces a reclamation of habitat, or a mere increase in detection? We leverage an increase in balcony birdwatching, a million eBird entries, and difference-in-difference techniques to test if urban avian species richness rose during India's COVID-19 lockdown. Controlling for effort, birdwatchers in the 20 most populous cities observed a 16% increase in the number of species during lockdown. While human activity stopped overnight, and noise and visual pollution decreased soon after, increased species diversity was observed 1–2 weeks later; evidence that gradual population recovery, not better detection, underlay our results. We find at-risk, and rare, species among those reclaiming cities, implying that reducing human disturbance in urban areas can protect threatened species. Increased species diversity likely derives from a reduction in noise and air pollution associated with the lockdown, implying that urban planners should consider conservation co-benefits of urban policies when designing sustainable cities.
</details>
<details> <summary>Media Coverage</summary>
[Nature India](https://www.nature.com/articles/d44151-022-00060-2)
</details>
</li> </ul>
<br>
* [**Saving the world from your couch: The heterogeneous medium-run benefits of COVID-19 lockdowns on air pollution**](https://iopscience.iop.org/article/10.1088/1748-9326/abee4d)  
(with Jean-Philippe Bonardi, [Quentin Gallea](https://www.quentingallea.com/), [Dimitrija Kalanoski](https://www.research.manchester.ac.uk/portal/dimitrija.kalanoski.html), [Rafael Lalive](https://sites.google.com/site/rafaellalive/), [Frederik Noack](https://frederiknoack.landfood.ubc.ca/), [Dominic Rohner](https://sites.google.com/site/dprohner/), and [Tommaso Sonno](http://www.tommasosonno.com/)). *Environmental Research Letters, 2021*
<ul> <li style="list-style-type: none;"> 
<details> <summary>[Click for Abstract] [[PDF]](/pdf/2021_saving_the_world.pdf)</summary>
In Spring 2020, COVID-19 led to an unprecedented halt in public and economic life across the globe. In an otherwise tragic time, this provides a unique natural experiment to investigate the environmental impact of such a (temporary) 'de-globalization'. Here, we estimate the medium-run impact of a battery of COVID-19 related lockdown measures on air quality across 162 countries, going beyond the existing short-run estimates from a limited number of countries. In doing so, we leverage a new dataset categorizing lockdown measures and tracking their implementation and release, extending to 31 August 2020. We find that domestic and international lockdown measures overall led to a decline in PM2.5 pollution by 45% and 35%, respectively. This substantial impact persists in the medium-run, even as lockdowns are lifted, there is, however, substantial heterogeneity across different types of lockdown measures, different countries, and different sources of pollution. We show that some country trajectories are much more appealing (with fewer COVID-19 casualties, less economic downturn and bigger pollution reductions) than others. Our results have important policy implications and highlight the potential to 'build back better' a sustainable economy where pollution can be curbed in a less economically costly way than during the COVID-19 pandemic.
</details>
<details> <summary>Media Coverage</summary>
[UBC Press Release](https://news.ubc.ca/2021/04/06/covid-19-lockdowns-only-reduced-air-pollution-in-some-parts-of-the-world/), [VoxEU](https://voxeu.org/article/pollution-reductions-during-lockdowns-can-teach-us-how-build-back-better), [The Conversation](https://theconversation.com/covid-19-lockdowns-improved-air-quality-in-some-cities-shedding-light-on-how-to-curb-pollution-158356), [I by IMD](https://iby.imd.org/sustainability/stay-home-to-save-the-world-not-so-fast/), [National Post](https://nationalpost.com/pmn/news-pmn/covid-19-lockdowns-improved-air-quality-in-some-cities-shedding-light-on-how-to-curb-pollution), [Global TV](https://globalnews.ca/video/7742442/ubc-study-finds-pollution-did-not-decrease-everywhere-during-pandemic/), [Vancouver is awesome](https://www.vancouverisawesome.com/coronavirus-covid-19-local-news/heres-why-covid-19-lockdowns-only-reduced-air-pollution-in-parts-of-the-world-3607865), [InfoTel](https://infotel.ca/newsitem/canada-saw-30-decrease-in-air-pollution-during-first-wave-lockdown-ubc-study/it82126), [24heures (French)](https://www.24heures.ch/la-pollution-a-baisse-beaucoup-plus-que-lactivite-economique-756413910716), [Radio Canada Internacional (Spanish)](https://www.rcinet.ca/es/2021/04/13/el-confinamiento-no-redujo-la-contaminacion-del-aire-tanto-como-se-esperaba/), [Spice Podcast](https://soundcloud.com/user-244969524-696484203/ubc-study-found-covid-19-lockdowns-only-reduced-air-pollution-in-some-parts-of-the-world)
</details>
</li> </ul>